import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // benovaSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  benovaSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Why Nova?",
    },
    {
      type: "doc",
      id: "ingenium",
      label: "The Challenge",
    },
    {
      type: "doc",
      id: "ing_on_cloud",
      label: "Success Story",
    },
    {
      type: "doc",
      id: "nova",
      label: "The Platform",
    },
    {
      type: "category",
      label: "Nexus — DevOps Foundation",
      description: "Automated toolchain for Ingenium modernization",
      items: [
        {
          type: "doc",
          id: "binean_nexus/intro",
          label: "Overview & Results",
        },
        {
          type: "doc",
          id: "binean_nexus/extension",
          label: "VS Code Extension",
        },
        {
          type: "doc",
          id: "binean_nexus/architecture",
          label: "Architecture",
        },
        {
          type: "doc",
          id: "binean_nexus/toolchain",
          label: "Toolchain",
        },
        {
          type: "doc",
          id: "binean_nexus/security",
          label: "Security & Compliance",
        },
      ],
    },
    {
      type: "category",
      label: "Orbit — Core Modernization",
      description: "Transform your insurance core",
      items: ["binean_orbit/intro"],
    },
    {
      type: "category",
      label: "Vista — Experience Design",
      description: "Next-generation user interfaces",
      items: ["binean_vista/intro"],
    },
    {
      type: "category",
      label: "Apex — Full Innovation",
      description: "Complete platform re-architecture",
      items: ["binean_apex/intro"],
    },
  ],
};

export default sidebars;
