import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // benovaSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  benovaSidebar: [
    'intro',
    {
          type: 'doc',
          id: 'ingenium',
          label: 'Ingenium',
    },
    {
          type: 'doc',
          id: 'nova',
          label: 'Nova',
    },
    {
      type: 'category',
      label: 'Nexus',
      description: 'Foundation of Connection',
      items: [
        {
          type: 'doc',
          id: 'binean_nexus/infrastructure',
          label: 'Infrastructure',
        },
        {
          type: 'doc',
          id: 'binean_nexus/devops',
          label: 'DevOps & CI/CD',
        },
        {
          type: 'doc',
          id: 'binean_nexus/vscode_extension',
          label: 'VS Code Extension',
        },
      ],
    },
    {
      type: 'category',
      label: 'Orbit',
      description: 'Core in Motion',
      items: [
        'binean_orbit/intro',
      ],
    },
    {
      type: 'category',
      label: 'Vista',
      description: 'Vision Unfolded',
      items: [
        'binean_vista/intro',
      ],
    },
    {
      type: 'category',
      label: 'Apex',
      description: 'Summit of Innovation',
      items: [
        'binean_apex/intro',
      ],
    },
    {
      type: 'category',
      label: 'Tutorial - Basics',
      items: [
        'tutorial-basics/create-a-page',
        'tutorial-basics/create-a-document',
        'tutorial-basics/create-a-blog-post',
        'tutorial-basics/deploy-your-site',
        'tutorial-basics/congratulations',
      ],
    },
    {
      type: 'category',
      label: 'Tutorial - Extras',
      items: [
        'tutorial-extras/manage-docs-versions',
        'tutorial-extras/translate-your-site',
      ],
    },
  ],
};

export default sidebars;
