import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // benovaSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  benovaSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Why Nova?",
    },
    {
      type: "doc",
      id: "ingenium",
      label: "The Challenge",
    },
    {
      type: "doc",
      id: "ing_on_cloud",
      label: "ING on Cloud",
    },
    {
      type: "doc",
      id: "nova",
      label: "The Platform",
    },
    {
      type: "category",
      label: "Nexus — DevOps Foundation",
      description: "Automated toolchain for Ingenium modernization",
      items: [
        {
          type: "doc",
          id: "binean_nexus/intro",
          label: "Overview & Results",
        },
        {
          type: "doc",
          id: "binean_nexus/extension",
          label: "VS Code Extension",
        },
        {
          type: "doc",
          id: "binean_nexus/toolchain",
          label: "Toolchain",
        },
        {
          type: "doc",
          id: "binean_nexus/security",
          label: "Security & Compliance",
        },
        {
          type: "category",
          label: "User Guides",
          description: "Step-by-step guides for each Nexus tool",
          items: [
            {
              type: "doc",
              id: "binean_nexus/guides/intro",
              label: "Getting Started",
            },
            {
              type: "doc",
              id: "binean_nexus/guides/benova",
              label: "benova — Environment Setup",
            },
            {
              type: "doc",
              id: "binean_nexus/guides/icomp",
              label: "icomp — COBOL Compiler",
            },
            {
              type: "doc",
              id: "binean_nexus/guides/iman",
              label: "iman — Server Manager",
            },
            {
              type: "doc",
              id: "binean_nexus/guides/isman",
              label: "isman — Management Server",
            },
            {
              type: "doc",
              id: "binean_nexus/guides/ipol",
              label: "ipol — Policy Manager",
            },
            {
              type: "doc",
              id: "binean_nexus/guides/nexus",
              label: "nexus — Utilities",
            },
            {
              type: "doc",
              id: "binean_nexus/guides/itun",
              label: "itun — SSH Tunnel",
            },
            {
              type: "doc",
              id: "binean_nexus/guides/extension",
              label: "VS Code Extension Guide",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Orbit — Core Modernization",
      description: "Transform your insurance core",
      items: ["binean_orbit/intro"],
    },
    {
      type: "category",
      label: "Vista — Experience Design",
      description: "Next-generation user interfaces",
      items: ["binean_vista/intro"],
    },
    {
      type: "category",
      label: "Apex — Full Innovation",
      description: "Complete platform re-architecture",
      items: ["binean_apex/intro"],
    },
  ],
};

export default sidebars;
